// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpk9ra5dDByNTC3OzxdIxWGD4bEXfGBMw',
    appId: '1:176954378537:web:e869e6d26d209ee4068f38',
    messagingSenderId: '176954378537',
    projectId: 'waitless-26eb4',
    authDomain: 'waitless-26eb4.firebaseapp.com',
    databaseURL: 'https://waitless-26eb4-default-rtdb.firebaseio.com',
    storageBucket: 'waitless-26eb4.firebasestorage.app',
    measurementId: 'G-ES0BH35F6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvP9OE7u6izEjfjdJMMKaxqxIGHCy1qQA',
    appId: '1:176954378537:android:000616fc7e73bb77068f38',
    messagingSenderId: '176954378537',
    projectId: 'waitless-26eb4',
    databaseURL: 'https://waitless-26eb4-default-rtdb.firebaseio.com',
    storageBucket: 'waitless-26eb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGrrLr00ep2h6gQAmkoAWJoyn6ybOByvI',
    appId: '1:176954378537:ios:2aff7134838c38e5068f38',
    messagingSenderId: '176954378537',
    projectId: 'waitless-26eb4',
    databaseURL: 'https://waitless-26eb4-default-rtdb.firebaseio.com',
    storageBucket: 'waitless-26eb4.firebasestorage.app',
    iosBundleId: 'com.example.waitless',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGrrLr00ep2h6gQAmkoAWJoyn6ybOByvI',
    appId: '1:176954378537:ios:2aff7134838c38e5068f38',
    messagingSenderId: '176954378537',
    projectId: 'waitless-26eb4',
    databaseURL: 'https://waitless-26eb4-default-rtdb.firebaseio.com',
    storageBucket: 'waitless-26eb4.firebasestorage.app',
    iosBundleId: 'com.example.waitless',
  );

}