import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import 'package:waitless/core/constants.dart';
import 'package:waitless/core/theme.dart';
import 'package:waitless/panels/auth/role_selection_screen.dart';
import 'package:waitless/panels/doctor/doc_home.dart';
import 'package:waitless/panels/patient/patient_home.dart';

// Generated by FlutterFire CLI.
import 'firebase_options.dart';
import 'panels/auth/splash_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Firebase must be initialised before any Firebase SDK call.
  // This also restores the previously saved Auth token so that
  // authStateChanges() can emit the persisted User on first listen.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Keep status bar transparent with dark icons (matches white AppBar).
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor:                   Colors.transparent,
      statusBarIconBrightness:          Brightness.dark,
      systemNavigationBarColor:         Colors.white,
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
  );

  // Lock to portrait — remove if landscape is required.
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  runApp(const WaitlessApp());
}

// ─────────────────────────────────────────────────────────────────
// WaitlessApp — MaterialApp root
// ─────────────────────────────────────────────────────────────────
class WaitlessApp extends StatelessWidget {
  const WaitlessApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Waitless',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,

      // _AuthGate is the REAL home. It never shows RoleSelectionScreen
      // to a user who is already logged in — it routes them directly
      // to their role-appropriate home screen.
      home: const SplashScreen(),
    );
  }
}

// ─────────────────────────────────────────────────────────────────
// _AuthGate — StreamBuilder wrapper for auth-state-driven routing
//
// BLACK BOOK — Why StreamBuilder instead of FutureBuilder here?
//   FutureBuilder fires once. StreamBuilder fires on every emission.
//   authStateChanges() emits again whenever the auth state changes
//   (login → logout → delete), so the UI reacts automatically
//   without any Navigator calls from service or dialog code.
// ─────────────────────────────────────────────────────────────────
class _AuthGate extends StatelessWidget {
  const _AuthGate();

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      // REQUIREMENT 1: listen to Firebase Auth session stream.
      // Firebase restores the saved token on app restart so this
      // stream immediately emits the persisted User without a login.
      stream: FirebaseAuth.instance.authStateChanges(),

      builder: (context, authSnapshot) {

        // ── State 1: Firebase is still initialising ──────────────
        // ConnectionState.waiting on the very first frame before
        // Firebase has replied. Show a branded splash to avoid flash.
        if (authSnapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(backgroundColor: AppColors.background);
        }

        // ── State 2: Nobody signed in ─────────────────────────────
        // authSnapshot.data is null → no active session.
        // Show role selection so the user can log in or register.
        if (!authSnapshot.hasData || authSnapshot.data == null) {
          return const RoleSelectionScreen();
        }

        // ── State 3: User is signed in ────────────────────────────
        // We have a User with a UID. Now we need to know whether
        // they are a patient or a doctor to route correctly.
        // This is a second async step so we use another FutureBuilder.
        final String uid = authSnapshot.data!.uid;
        return _RoleRouter(uid: authSnapshot.data!.uid);
      },
    );
  }
}

class _RoleRouter extends StatefulWidget {
  const _RoleRouter({required this.uid});
  final String uid;

  @override
  State<_RoleRouter> createState() => _RoleRouterState();
}

class _RoleRouterState extends State<_RoleRouter> {
  late final Future<String?> _roleFuture;

  @override
  void initState() {
    super.initState();
    _roleFuture = _getRole();
  }

  Future<String?> _getRole() async {
    final db = FirebaseFirestore.instance;
    final patientDoc = await db.collection('patients').doc(widget.uid).get();
    if (patientDoc.exists) return 'patient';
    final doctorDoc = await db.collection('doctors').doc(widget.uid).get();
    if (doctorDoc.exists) return 'doctor';
    return null;
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<String?>(
      future: _roleFuture,
      builder: (context, snap) {
        if (snap.connectionState == ConnectionState.waiting) {
          return const _SplashScreen();
        }
        final role = snap.data;
        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (!context.mounted) return;
          final dest = switch (role) {
            'doctor'  => const DocHomeScreen(),
            'patient' => const PatientHomeScreen(),
            _         => const RoleSelectionScreen(),
          };
          Navigator.pushAndRemoveUntil(
            context,
            MaterialPageRoute(builder: (_) => dest),
                (_) => false,
          );
        });
        return const _SplashScreen();
      },
    );
  }
}

/*class _RoleRouterState extends State<_RoleRouter> {
  late final Future<String?> _roleFuture; // ← ADD THIS

  @override
  void initState() {
    super.initState();
    _roleFuture = _getRole(); // ← cache it ONCE here
  }

  Future<String?> _getRole() async {
    final db = FirebaseFirestore.instance;
    final patientDoc = await db.collection('patients').doc(widget.uid).get();
    if (patientDoc.exists) {
      return patientDoc.data()?['role'] as String? ?? 'patient';
    }
    final doctorDoc = await db.collection('doctors').doc(widget.uid).get();
    if (doctorDoc.exists) {
      return doctorDoc.data()?['role'] as String? ?? 'doctor';
    }
    return null;
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<String?>(
      future: _roleFuture, // ← use cached future, NOT _getRole() directly
      builder: (context, roleSnap) {
        if (roleSnap.connectionState == ConnectionState.waiting) {
          return const _SplashScreen();
        }

        final String? role = roleSnap.data;

        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (!context.mounted) return;
          final Widget destination = switch (role) {
            'doctor'  => const DocHomeScreen(),
            'patient' => const PatientHomeScreen(),
            _         => const RoleSelectionScreen(),
          };
          Navigator.pushAndRemoveUntil(
            context,
            MaterialPageRoute(builder: (_) => destination),
                (_) => false,
          );
        });

        return const _SplashScreen();
      },
    );
  }
}*/

// ─────────────────────────────────────────────────────────────────
// _SplashScreen — shown while Firebase / Firestore resolves
//
// Branded loading screen so the user sees the app name rather than
// a white flash during the async auth + role lookup.
// ─────────────────────────────────────────────────────────────────
class _SplashScreen extends StatelessWidget {
  const _SplashScreen();

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      backgroundColor: AppColors.background,
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              'Waitless',
              style: TextStyle(
                fontFamily:  'Nunito',
                fontSize:    36,
                fontWeight:  FontWeight.w800,
                color:       AppColors.primary,
                letterSpacing: -1.0,
              ),
            ),
            SizedBox(height: 24),
            CircularProgressIndicator(
              color:       AppColors.primary,
              strokeWidth: 2.5,
            ),
          ],
        ),
      ),
    );
  }
}
// ADD THIS TO THE VERY BOTTOM OF main.dart
class AuthPageNavigator extends StatelessWidget {
  const AuthPageNavigator({super.key});

  @override
  Widget build(BuildContext context) {
    // This points to the private _AuthGate logic Claude wrote
    return const _AuthGate();
  }
}